SELECT * FROM MEMBER;
DELETE FROM MEMBER WHERE USERNAME ='홍나리';
ALTER TABLE MEMBER MODIFY PASSWORD VARCHAR2(200);
UPDATE MEMBER SET PASSWORD='+lhdichR3TOKcNz1Naoqkv7ng23Wr/EiZYPojgmWKT8WvACcZSgm4PxccGaVoDzdzjcvE57/TROVnabx9dPqvg==';